#!/bin/bash

##### Troubleshooting #####
# Requires docker and the image prepared by yaqwsx:  https://github.com/yaqwsx/KiKit
# Run this command from within the PCB project directory (this file must be located in the same directory)
# docker run -it -v "$(pwd):/kikit" yaqwsx/kikit kikit/makePanel

##### Troubleshooting #####
# Line endings must be LF (not CRLF)

# M.Ruppe - Core Electronics

now=$(date +"%Y-%m-%d")
kikit panelize \
grid \
--gridsize 3 13 \
--space 2 \
--radius 1 \
--htabs 0 \
--vtabs 1 \
--tabwidth 12 \
--vcuts \
--railsTb 13.655 \
--fiducials 12.5 7.5 1.5 3 \
--tooling 5 5 3 \
kikit/PiicoDev-Raspberry-Pi-Adapter.kicad_pcb \
"kikit/P82 v10 $now".kicad_pcb
